version: "3.8"

services:
  cursok8s:
    build:
      context: .
      dockerfile: Dockerfile
    image: cursok8s:latest
    container_name: cursok8s
    ports:
      - "8086:80"
    restart: unless-stopped
